server {
    listen 80;
    server_name _;

    root /var/www/html/web;
    index index.php index.html;

    # Запрет PHP-выполнения в uploads
    location ~* /app/uploads/.*\.php$ {
      deny all;
    }

    # ЧПУ и статика
    location / {
      try_files $uri $uri/ /index.php?$args;
    }

    # Передаём .php в FPM на TCP-9000
    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_index index.php;
    }

    # Запрет доступа к скрытым файлам (.env, .gitignore…)
    location ~ /\. {
      deny all;
    }
}
